#!/usr/bin/env python3
"""
Generate token-bridge.css from an active acss-kit theme + vocab.json.

Reads the vocabulary mapping at vocab.json (relative to this script's
assets/utilities/ dir) and the project's light.css / dark.css theme files,
then emits a token-bridge.css that aliases acss-kit role names to the
fpkit-style names utility classes expect.

Generator/validator contract: emits CSS on stdout (or writes to --out);
errors on stderr; exit 0 on success, 1 on failure, 2 on usage error.

Usage:
    python generate_bridge.py --theme-dir=<dir> [--out=<file>]
    python generate_bridge.py --self-test

--theme-dir   Directory containing light.css and/or dark.css.
--out         Output path. Defaults to stdout when omitted.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
_VOCAB_PATH = _SCRIPT_DIR.parent / "assets" / "utilities" / "vocab.json"

# Default fallback hex values for light and dark when no theme is present.
_FALLBACKS_LIGHT = {
    "primary":    "#2563eb",
    "danger":     "#dc2626",
    "success":    "#16a34a",
    "warning":    "#ca8a04",
    "info":       "#0284c7",
    "background": "#ffffff",
}
_FALLBACKS_DARK = {
    "primary":    "#7dd3fc",
    "danger":     "#f87171",
    "success":    "#4ade80",
    "warning":    "#fbbf24",
    "info":       "#38bdf8",
    "background": "#0f172a",
}

_CSS_VAR_RE = re.compile(r"--color-([\w-]+)\s*:\s*([^;]+);")


def _parse_theme(css_text: str) -> dict[str, str]:
    """Extract --color-* variable values from a theme CSS block."""
    result: dict[str, str] = {}
    for m in _CSS_VAR_RE.finditer(css_text):
        result[m.group(1)] = m.group(2).strip()
    return result


def _extract_block(css_text: str, selector: str) -> str:
    """Return the content of the first matching CSS selector block."""
    pattern = re.compile(
        re.escape(selector) + r"\s*\{([^}]*)\}", re.DOTALL
    )
    m = pattern.search(css_text)
    return m.group(1) if m else ""


def _load_theme(theme_dir: Path) -> tuple[dict[str, str], dict[str, str]]:
    """Return (light_vars, dark_vars) dicts keyed by role name."""
    light_vars: dict[str, str] = {}
    dark_vars: dict[str, str] = {}

    light_file = theme_dir / "light.css"
    dark_file = theme_dir / "dark.css"

    if light_file.is_file():
        css = light_file.read_text(encoding="utf-8")
        root_block = _extract_block(css, ":root")
        light_vars = _parse_theme(root_block or css)

    if dark_file.is_file():
        css = dark_file.read_text(encoding="utf-8")
        dark_block = _extract_block(css, '[data-theme="dark"]')
        if not dark_block:
            dark_block = _extract_block(css, ":root")
        dark_vars = _parse_theme(dark_block or css)

    return light_vars, dark_vars


def _hex(role: str, vars_: dict[str, str], fallbacks: dict[str, str]) -> str:
    val = vars_.get(role, "")
    if val.startswith("#"):
        return val
    return fallbacks.get(role, "#000000")


def _var(role: str, vars_: dict[str, str], fallbacks: dict[str, str]) -> str:
    fb = _hex(role, vars_, fallbacks)
    return f"var(--color-{role}, {fb})"


def generate(theme_dir: Path, vocab_path: Path = _VOCAB_PATH) -> str:
    """Return the generated token-bridge.css content as a string."""
    vocab = json.loads(vocab_path.read_text(encoding="utf-8"))
    light_vars, dark_vars = _load_theme(theme_dir)

    roles = vocab.get("roles", {})        # acss-kit name → fpkit name
    derived = vocab.get("derived", {})    # fpkit name → mix recipe
    fallback = vocab.get("fallback", {})  # fpkit name → use-this-role instead

    lines = [
        "/*",
        " * token-bridge.css — generated by generate_bridge.py",
        " * DO NOT EDIT manually. Regenerate via /utility-bridge or /theme-update.",
        " *",
        " * Aliases acss-kit role names to the fpkit-style names utility classes",
        " * reference. Both :root and [data-theme=\"dark\"] blocks are mandatory.",
        " */",
        "",
        ":root {",
    ]

    # Direct role renames (e.g. danger → error)
    for kit_role, fpkit_name in roles.items():
        fb = _hex(kit_role, light_vars, _FALLBACKS_LIGHT)
        lines.append(f"  --color-{fpkit_name}: var(--color-{kit_role}, {fb});")

    # Derived values (color-mix computations)
    for fpkit_name, recipe in derived.items():
        from_role = recipe["from"]
        fb_light = _hex(from_role, light_vars, _FALLBACKS_LIGHT)
        bg_light = _hex("background", light_vars, _FALLBACKS_LIGHT)
        mix_expr = (recipe["mix"]
                    .replace("{light}", fb_light)
                    .replace("{bg}", bg_light))
        lines.append(f"  --color-{fpkit_name}: {mix_expr};")

    # Fallback aliases (e.g. secondary → primary)
    for fpkit_name, kit_role in fallback.items():
        fb = _hex(kit_role, light_vars, _FALLBACKS_LIGHT)
        lines.append(f"  --color-{fpkit_name}: var(--color-{kit_role}, {fb});")

    lines += ["}", ""]

    lines.append('[data-theme="dark"] {')

    for kit_role, fpkit_name in roles.items():
        fb = _hex(kit_role, dark_vars, _FALLBACKS_DARK)
        lines.append(f"  --color-{fpkit_name}: var(--color-{kit_role}, {fb});")

    for fpkit_name, recipe in derived.items():
        from_role = recipe["from"]
        fb_dark = _hex(from_role, dark_vars, _FALLBACKS_DARK)
        bg_dark = _hex("background", dark_vars, _FALLBACKS_DARK)
        mix_expr = (recipe.get("mix-dark", recipe["mix"])
                    .replace("{dark}", fb_dark)
                    .replace("{light}", fb_dark)
                    .replace("{bg-dark}", bg_dark)
                    .replace("{bg}", bg_dark))
        lines.append(f"  --color-{fpkit_name}: {mix_expr};")

    for fpkit_name, kit_role in fallback.items():
        fb = _hex(kit_role, dark_vars, _FALLBACKS_DARK)
        lines.append(f"  --color-{fpkit_name}: var(--color-{kit_role}, {fb});")

    lines += ["}", ""]
    return "\n".join(lines)


def self_test() -> int:
    import tempfile

    passed = 0
    failed = 0

    def run(name: str, theme_files: dict, checks: list[str],
            absent: list[str] | None = None) -> None:
        nonlocal passed, failed
        with tempfile.TemporaryDirectory() as tmpdir:
            theme_dir = Path(tmpdir)
            for fname, content in theme_files.items():
                (theme_dir / fname).write_text(content, encoding="utf-8")
            try:
                css = generate(theme_dir)
            except Exception as exc:
                print(f"FAIL: {name} — exception: {exc}")
                failed += 1
                return
            ok = all(chk in css for chk in checks)
            if absent:
                ok = ok and all(a not in css for a in absent)
            if ok:
                print(f"PASS: {name}")
                passed += 1
            else:
                missing = [c for c in checks if c not in css]
                unexpected = [a for a in (absent or []) if a in css]
                print(f"FAIL: {name} — missing={missing} unexpected={unexpected}")
                print("  CSS snippet:", css[:500])
                failed += 1

    run(
        "no theme files → uses fallback hex values",
        {},
        ["--color-error: var(--color-danger, #dc2626);",
         "--color-error-bg:",
         '[data-theme="dark"]'],
    )
    run(
        "light.css with custom danger hex → bridge uses it",
        {"light.css": ":root { --color-danger: #e11d48; }"},
        ["--color-error: var(--color-danger, #e11d48);"],
    )
    run(
        "dark.css with custom danger hex → dark block uses it",
        {
            "light.css": ":root { --color-danger: #dc2626; }",
            "dark.css": '[data-theme="dark"] { --color-danger: #fca5a5; }',
        },
        ['[data-theme="dark"]',
         "--color-error: var(--color-danger, #fca5a5);"],
    )
    run(
        "both :root blocks emitted",
        {},
        [":root {", '[data-theme="dark"] {'],
    )
    run(
        "secondary fallback alias emitted",
        {},
        ["--color-secondary:"],
    )
    run(
        "surface-secondary alias emitted",
        {},
        ["--color-surface-secondary:"],
    )

    total = passed + failed
    if failed:
        print(f"\n{failed}/{total} self-test(s) FAILED")
        return 1
    print(f"\nAll {total} self-tests PASSED")
    return 0


def main() -> int:
    args = sys.argv[1:]

    if "--self-test" in args:
        return self_test()

    theme_dir_str: str | None = None
    out_path: str | None = None
    for a in args:
        if a.startswith("--theme-dir="):
            theme_dir_str = a.split("=", 1)[1]
        elif a.startswith("--out="):
            out_path = a.split("=", 1)[1]

    if not theme_dir_str:
        print("Usage: generate_bridge.py --theme-dir=<dir> [--out=<file>]",
              file=sys.stderr)
        return 2

    theme_dir = Path(theme_dir_str).resolve()
    if not theme_dir.is_dir():
        print(f"Error: --theme-dir={theme_dir} does not exist", file=sys.stderr)
        return 1

    try:
        css = generate(theme_dir)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    if out_path:
        Path(out_path).write_text(css, encoding="utf-8")
    else:
        print(css, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
