#!/usr/bin/env python3
"""
Convert a theme.tokens.json file into CSS theme files.

Usage:
    python tokens_to_css.py <tokens.json> [--out-dir=<dir>]
    python tokens_to_css.py --stdin [--out-dir=<dir>]   (reads JSON from stdin)
    python tokens_to_css.py --self-test

Output: writes light.css and/or dark.css (and brand-<name>.css for each brand)
        to --out-dir (default: current directory). Prints file paths written.

Exit codes: 0 = success, 1 = validation error, 2 = usage/IO error.

CSS variable convention (CLAUDE.md §CSS variable naming):
  - Token DEFINITIONS emit raw values (`--color-primary: #4f46e5;`). A
    self-referential definition (`--x: var(--x, …)`) is a CSS cycle →
    guaranteed-invalid, so it would never apply. The `var(--token, <fallback>)`
    fallback convention applies to CONSUMERS (components/utilities), not here.
  - :root { } for light mode tokens.
  - [data-theme="dark"] { } for dark mode tokens.
  - Brand files use both selectors with only overridden roles.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(__file__))
from _tokens import (  # noqa: E402
    DARK_SELECTOR,
    LIGHT_SELECTOR,
    SCALE_KINDS,
    format_palette,
    format_scales,
    format_typography,
)


LIGHT_HEADER = """\
/* light.css — semantic role tokens for the light theme.
 * Generated by acss-kit /theme-create.
 * WCAG AA verified by validate_theme.py.
 */
"""

DARK_HEADER = """\
/* dark.css — semantic role tokens for the dark theme.
 * Generated by acss-kit /theme-create.
 * Scoped under [data-theme="dark"] — set this attribute on <html>.
 */
"""

BRAND_HEADER = """\
/* brand-{name}.css — brand color overrides.
 * Generated by acss-kit /theme-brand.
 * Layer this import AFTER light.css and dark.css.
 */
"""

SPACE_RADIUS_HEADER = """\
/* space-radius.css — spacing and corner-radius scale tokens.
 * Generated by acss-kit. Mode-independent (single :root block).
 * --space-* and --radius-* mirror DESIGN.md spacing/rounded.
 */
"""

TYPOGRAPHY_HEADER = """\
/* typography.css — typography composite tokens.
 * Generated by acss-kit. Mode-independent (single :root block).
 * --font-<role>-{family,size,weight,line,tracking} mirror DESIGN.md typography.
 */
"""


def _write_light(palette: dict[str, str], out_dir: Path) -> Path:
    content = LIGHT_HEADER + "\n" + format_palette(palette, LIGHT_SELECTOR)
    path = out_dir / "light.css"
    path.write_text(content, encoding="utf-8")
    return path


def _write_dark(palette: dict[str, str], out_dir: Path) -> Path:
    content = DARK_HEADER + "\n" + format_palette(palette, DARK_SELECTOR)
    path = out_dir / "dark.css"
    path.write_text(content, encoding="utf-8")
    return path


def _write_brand(name: str, overrides: dict, out_dir: Path) -> Path:
    header = BRAND_HEADER.replace("{name}", name)
    light_overrides = overrides.get("light", overrides)
    dark_overrides = overrides.get("dark", {})
    content = header + "\n"
    if light_overrides:
        content += format_palette(light_overrides, LIGHT_SELECTOR) + "\n"
    if dark_overrides:
        content += format_palette(dark_overrides, DARK_SELECTOR) + "\n"
    path = out_dir / f"brand-{name}.css"
    path.write_text(content, encoding="utf-8")
    return path


def _write_space_radius(spacing: dict, rounded: dict, out_dir: Path) -> Path:
    scales = []
    if spacing:
        scales.append(("Spacing", SCALE_KINDS["spacing"][0], spacing))
    if rounded:
        scales.append(("Radius", SCALE_KINDS["rounded"][0], rounded))
    content = SPACE_RADIUS_HEADER + "\n" + format_scales(scales, LIGHT_SELECTOR)
    path = out_dir / "space-radius.css"
    path.write_text(content, encoding="utf-8")
    return path


def _write_typography(typography: dict, out_dir: Path) -> Path:
    content = TYPOGRAPHY_HEADER + "\n" + format_typography(typography, LIGHT_SELECTOR)
    path = out_dir / "typography.css"
    path.write_text(content, encoding="utf-8")
    return path


def process(tokens: dict, out_dir: Path) -> list[str]:
    """Write CSS files from a tokens dict. Returns list of written paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    modes = tokens.get("modes", {})
    if "light" in modes:
        written.append(str(_write_light(modes["light"], out_dir)))
    if "dark" in modes:
        written.append(str(_write_dark(modes["dark"], out_dir)))
    for brand_name, overrides in tokens.get("brands", {}).items():
        written.append(str(_write_brand(brand_name, overrides, out_dir)))
    # Non-color token kinds (mode-independent). Additive: only emit when present,
    # so colors-only input remains byte-identical.
    spacing = tokens.get("spacing", {})
    rounded = tokens.get("rounded", {})
    if spacing or rounded:
        written.append(str(_write_space_radius(spacing, rounded, out_dir)))
    typography = tokens.get("typography", {})
    if typography:
        written.append(str(_write_typography(typography, out_dir)))
    return written


def self_test() -> int:
    import tempfile

    passed = 0
    failed = 0

    def run(name: str, tokens: dict, expected_files: list[str],
            checks: list[str], absent_files: list[str] | None = None) -> None:
        nonlocal passed, failed
        with tempfile.TemporaryDirectory() as tmpdir:
            out_dir = Path(tmpdir)
            written = process(tokens, out_dir)
            written_names = {Path(p).name for p in written}
            ok = set(expected_files) <= written_names
            if absent_files:
                ok = ok and not (set(absent_files) & written_names)
            combined = "".join(
                (out_dir / f).read_text(encoding="utf-8")
                for f in expected_files
                if (out_dir / f).exists()
            )
            ok = ok and all(chk in combined for chk in checks)
            if ok:
                print(f"PASS: {name}")
                passed += 1
            else:
                missing_files = set(expected_files) - written_names
                missing_checks = [c for c in checks if c not in combined]
                unexpected = set(absent_files or []) & written_names
                print(f"FAIL: {name} — missing_files={missing_files} missing_checks={missing_checks} unexpected_files={unexpected}")
                failed += 1

    run(
        "light mode only",
        {"modes": {"light": {"--color-primary": "#4f46e5", "--color-background": "#ffffff"}}},
        ["light.css"],
        [":root {", "--color-primary: #4f46e5;",
         "--color-background: #ffffff;"],
    )
    run(
        "dark mode written to correct selector",
        {"modes": {"dark": {"--color-primary": "#7dd3fc"}}},
        ["dark.css"],
        ['[data-theme="dark"] {', "--color-primary: #7dd3fc;"],
    )
    run(
        "both modes",
        {"modes": {
            "light": {"--color-primary": "#2563eb"},
            "dark":  {"--color-primary": "#93c5fd"},
        }},
        ["light.css", "dark.css"],
        [":root {", '[data-theme="dark"] {'],
    )
    run(
        "brand file written",
        {"brands": {"forest": {"light": {"--color-primary": "#2f7a4d"}, "dark": {"--color-primary": "#4ade80"}}}},
        ["brand-forest.css"],
        ["brand-forest.css", ":root {", '[data-theme="dark"] {',
         "--color-primary: #2f7a4d;"],
    )
    run(
        "unknown role not emitted",
        {"modes": {"light": {"--color-unknown-custom": "#ff0000", "--color-primary": "#2563eb"}}},
        ["light.css"],
        ["--color-primary"],
    )
    run(
        "colors-only input does not emit token files (back-compat)",
        {"modes": {"light": {"--color-primary": "#2563eb"}}},
        ["light.css"],
        [],
        absent_files=["space-radius.css", "typography.css"],
    )
    run(
        "spacing + rounded emit space-radius.css",
        {"spacing": {"md": "1rem", "lg": "1.5rem"}, "rounded": {"sm": "0.25rem", "full": "9999px"}},
        ["space-radius.css"],
        ["--space-md: 1rem;",
         "--radius-full: 9999px;",
         "/* Spacing */", "/* Radius */"],
    )
    run(
        "typography emits flattened --font-<role>-<sub>",
        {"typography": {"body-md": {"family": "Public Sans", "size": "1rem", "weight": "400", "line": "1.5"}}},
        ["typography.css"],
        ["--font-body-md-family: Public Sans;",
         "--font-body-md-size: 1rem;",
         "--font-body-md-weight: 400;"],
    )

    total = passed + failed
    if failed:
        print(f"\n{failed}/{total} self-test(s) FAILED")
        return 1
    print(f"\nAll {total} self-tests PASSED")
    return 0


def main() -> int:
    args = sys.argv[1:]

    if "--self-test" in args:
        return self_test()

    out_dir = Path(".")
    use_stdin = False
    input_path: Path | None = None

    for a in args:
        if a == "--stdin":
            use_stdin = True
        elif a.startswith("--out-dir="):
            out_dir = Path(a.split("=", 1)[1])
        elif not a.startswith("--"):
            input_path = Path(a)

    if not use_stdin and input_path is None:
        print("usage: tokens_to_css.py <tokens.json> [--out-dir=<dir>]", file=sys.stderr)
        return 2

    try:
        if use_stdin:
            tokens = json.load(sys.stdin)
        else:
            tokens = json.loads(input_path.read_text(encoding="utf-8"))  # type: ignore[union-attr]
    except Exception as e:
        print(f"error reading tokens: {e}", file=sys.stderr)
        return 2

    written = process(tokens, out_dir)
    if not written:
        print("tokens_to_css: nothing to write (no modes or brands in tokens)", file=sys.stderr)
        return 1

    for f in written:
        print(f"wrote: {f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
